FIND_PATH(MAXFLOW_INCLUDE_DIR
          maxflowlib.h
          HINTS "$ENV{MAXFLOW_ROOT}"
)

FIND_PATH(MAXFLOW_LIBRARY_DIR
          MaxFlow.lib
          HINTS "$ENV{MAXFLOW_ROOT}" "$ENV{MAXFLOW_ROOT}/lib" "$ENV{MAXFLOW_ROOT}/lib/x64"
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MaxFlow DEFAULT_MSG MAXFLOW_INCLUDE_DIR)

set (MAXFLOW_LIBRARIES "${MAXFLOW_LIBRARY_DIR}/MaxFlow.lib")

MARK_AS_ADVANCED( MAXFLOW_INCLUDE_DIR )